# Generated by Django 4.2 on 2023-05-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuentaIg',
        ),
        migrations.DeleteModel(
            name='PublicacionIg',
        ),
    ]
