# Generated by Django 4.2 on 2023-05-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0005_delete_cuentaig_delete_publicacionig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaIg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('iguser', models.CharField(max_length=255)),
                ('ispass', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionIg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('piefoto', models.CharField(max_length=255)),
                ('fecha', models.CharField(max_length=255)),
                ('imagen', models.CharField(max_length=255)),
            ],
        ),
    ]
