# Generated by Django 4.2 on 2023-05-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_rename_ispass_cuentaig_igpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionig',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
