# Generated by Django 4.1.7 on 2023-05-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_publicacionig_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionig',
            name='fecha',
            field=models.CharField(max_length=255),
        ),
    ]
